services:
  - type: web
    name: live-tasks
    env: elixir
    rootDir: live_tasks
    buildCommand: |
      mix deps.get
      mix assets.deploy
      mix compile
    startCommand: MIX_ENV=prod mix phx.server
    envVars:
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
