services:
  - type: web
    name: live-tasks
    env: elixir
    rootDir: live_tasks\lib\live_tasks         # 👈 tells Render to cd into this folder before build
    buildCommand: mix deps.get && mix compile
    startCommand: mix phx.server
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
